# Generated by Django 4.1.5 on 2023-01-31 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_petrol', models.FloatField()),
                ('rate_disel', models.FloatField()),
                ('total_budget', models.FloatField()),
                ('fiscalyear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.fiscalyear')),
            ],
        ),
    ]
