# Generated by Django 4.1.5 on 2023-02-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='liscen_no',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
